name: eHealth.Business
favicon: null
layout_spectrum: 0.74323
typography_spectrum: 0.80469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#18b4cb'
    - '#59a246'
    - '#21637b'
    - '#02161c'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
